name: bluehorizon
version: 2.0.9
summary: Horizon Decentralized Autonomous Edge Compute System...
description: This snap includes all Horizon system control components...
confinement: devmode
epoch: 0
grade: devel

apps:
  anax:
    command: scripts/anax/anax.sh
    daemon: simple
    plugs: [firewall-control, network, network-bind]
    restart-condition: always

parts:
  anax:
    plugin: make
    build-packages:
      - golang
      - git
    stage-packages:
      - bash
      - curl
      - gettext
      - jq
    source: https://github.com/open-horizon/anax.git

  anax-ui:
    plugin: make
    build-packages:
      - git
      - nodejs
    stage-packages:
      - bash
    source: https://github.com/open-horizon/anax-ui.git

  horizon-distribution:
    plugin: dump
    source: distribution/
